name: dartpedia
description: A Dart library for fetching data through Wikimedia API endpoints.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
