name: wikidart
description: A Dart library for fetching data through Wikimedia API endpoints.
version: 0.0.1
homepage: https://github.com/flikkr/wikidart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^1.2.2
  tuple: ^2.0.2

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.25.8
